{
 "title": "AmbientWeather Local Server",
 "description": "An example dashboard for displaying prometheus metrics from an AmbientWeather local server.",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   { "name": "LogSource", "query": "loki" },
   {
    "name": "WeatherStation",
    "query": {
     "query": "label_values(ambientweather_api_temperature_f, macAddress)"
    }
   },
   {
    "name": "WeatherStationType",
    "query": {
     "query": "label_values(ambientweather_api_temperature_f, stationType)"
    }
   },
   {
    "name": "MeasurementType",
    "query": {
     "query": "label_values(ambientweather_api_temperature_f, type)"
    }
   },
   {
    "name": "Source",
    "query": {
     "query": "label_values(ambientweather_api_temperature_f, source)"
    }
   }
  ]
 },
 "panels": [
  { "title": "README", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "# AmbientWeather Local Server Dashboard\n\n## Filters\n\nFilters can be applied to view different subsets of the data.\n\n* Datasource - Your Prometheus Datasource\n* WeatherStation - if you have more than one station, you can filter by MAC address here\n* WeatherStationType - if you have more than one station, you can filter by the Station Model here\n* MeasurementType - Indoor/Outdoor, etc\n* Source - where the metric originated from, i.e. Local vs. Cloud. You will only have data from the Cloud if you have enabled AWN enrichment\n\n## Container Events Annotations\n\nA toggle is provided for displaying docker container events as annotations.  This toggle requires you have [DocGraf](https://github.com/philosowaffle/docgraf) running and reporting these events."
   }
  },
  {
   "title": "Current",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temperature",
     "type": "stat",
     "gridPos": { "h": 3, "w": 7, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ambientweather_api_temperature_f{type=~\"$MeasurementType\", macAddress=~\"$WeatherStation\", stationType=~\"$WeatherStationType\", source=~\"$Source\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Wind Direction",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 7, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "degree" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ambientweather_api_winddirection_deg{type=\"wind\", macAddress=~\"$WeatherStation\", stationType=~\"$WeatherStationType\", source=~\"$Source\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Gust",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 11, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "velocitymph" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ambientweather_api_windspeed_mph{type=\"gust\", macAddress=~\"$WeatherStation\", stationType=~\"$WeatherStationType\", source=~\"$Source\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Outdoor DewPoint",
     "type": "stat",
     "description": "Only available from Cloud",
     "gridPos": { "h": 3, "w": 4, "x": 15, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ambientweather_api_dewpoint_f{stationType=~\"$WeatherStationType\", type=~\"outdoor\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "UV Index",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 5, "x": 19, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ambientweather_api_uv_index{macAddress=~\"$WeatherStation\", stationType=~\"$WeatherStationType\", source=~\"$Source\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Feels Like Temperature",
     "type": "stat",
     "description": "Only available from Cloud",
     "gridPos": { "h": 3, "w": 7, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ambientweather_api_feelslike_f{type=~\"$MeasurementType\", macAddress=~\"$WeatherStation\", stationType=~\"$WeatherStationType\", source=~\"cloud\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Wind Speed",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 7, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "velocitymph" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ambientweather_api_windspeed_mph{type=\"wind\", macAddress=~\"$WeatherStation\", stationType=~\"$WeatherStationType\", source=~\"$Source\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Rain",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 11, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "lengthin" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ambientweather_api_rain_in{type=\"event\", macAddress=~\"$WeatherStation\", stationType=~\"$WeatherStationType\", source=~\"$Source\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Indoor DewPoint",
     "type": "stat",
     "description": "Only available from Cloud",
     "gridPos": { "h": 3, "w": 4, "x": 15, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ambientweather_api_dewpoint_f{stationType=~\"$WeatherStationType\", type=~\"indoor\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "AmbientWeather Station Data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temperature",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
     "targets": [
      {
       "expr": "ambientweather_api_temperature_f{macAddress=~\"$WeatherStation\", stationType=~\"$WeatherStationType\", type=~\"$MeasurementType\", source=~\"$Source\"}",
       "legendFormat": "{{type}}"
      },
      {
       "expr": "ambientweather_api_feelslike_f{macAddress=~\"$WeatherStation\", stationType=~\"$WeatherStationType\", type=~\"$MeasurementType\"}",
       "legendFormat": "{{type}} feels like"
      }
     ]
    },
    {
     "title": "Wind",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "velocitymph" } },
     "targets": [
      {
       "expr": "ambientweather_api_windspeed_mph{type=\"wind\", macAddress=~\"$WeatherStation\", stationType=~\"$WeatherStationType\", source=~\"$Source\"}",
       "legendFormat": "{{type}}"
      },
      {
       "expr": "ambientweather_api_windspeed_mph{type=\"gust\", source=~\"$Source\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Wind Direction",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "degree" } },
     "targets": [
      {
       "expr": "ambientweather_api_winddirection_deg{type=\"wind\", macAddress=~\"$WeatherStation\", stationType=~\"$WeatherStationType\", source=~\"$Source\"}",
       "legendFormat": "{{type}}"
      },
      {
       "expr": "avg_over_time(ambientweather_api_winddirection_deg{type=\"wind\", source=~\"$Source\"}[10m])",
       "legendFormat": "direction avg"
      }
     ]
    },
    {
     "title": "UV Index",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "ambientweather_api_uv_index{macAddress=~\"$WeatherStation\", stationType=~\"$WeatherStationType\", source=~\"$Source\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Rain",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "lengthin" } },
     "targets": [
      {
       "expr": "rate(ambientweather_api_rain_in{type=\"event\", macAddress=~\"$WeatherStation\", stationType=~\"$WeatherStationType\", source=~\"$Source\"}[5m])",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Yearly Rain",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "lengthin" } },
     "targets": [
      {
       "expr": "ambientweather_api_rain_in{type=\"yearly\", macAddress=~\"$WeatherStation\", stationType=~\"$WeatherStationType\", source=~\"$Source\"}",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "AWLS Service Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 4, "w": 18, "x": 0, "y": 4 },
     "options": {
      "content": "# AmbientWeather Local Server Monitoring\n"
     }
    },
    {
     "title": "Version",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 18, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ambientweather_api_build_info{}"
      }
     ]
    },
    {
     "title": "DotNet Runtime",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 21, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ambientweather_api_build_info{}"
      }
     ]
    },
    {
     "title": "OS Version",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 18, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ambientweather_api_build_info{}"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 21, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "dtdurations" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "time() - process_start_time_seconds{job=\"ambientweather\"}"
      }
     ]
    },
    {
     "title": "Logs",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 10, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by(level) (rate({container_name=\"ambientweather\"} | json | __error__ != `JSONParserErr` [1m]))",
       "legendFormat": "{{level}}"
      }
     ]
    },
    {
     "title": "CPU",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 14, "x": 10, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{job=\"ambientweather\"}[$__interval])",
       "legendFormat": "{{instance}} CPU Process Seconds"
      }
     ]
    },
    {
     "title": "Logs",
     "type": "logs",
     "gridPos": { "h": 16, "w": 10, "x": 0, "y": 12 },
     "targets": [
      {
       "bucketAggs": [
        { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "{container_name=\"ambientweather\"}",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 14, "x": 10, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "dotnet_total_memory_bytes{job=\"ambientweather\"}",
       "legendFormat": "DotNet Total Memory Bytes"
      },
      {
       "expr": "process_working_set_bytes{job=\"ambientweather\"}",
       "legendFormat": "Process Working Set (RAM)"
      },
      {
       "expr": "process_private_memory_bytes{job=\"ambientweather\"}",
       "legendFormat": "Process Private Memory Bytes"
      },
      {
       "expr": "process_virtual_memory_bytes{job=\"ambientweather\"}",
       "legendFormat": "Process Virtual Memory Bytes"
      }
     ]
    },
    {
     "title": "Num Threads",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 14, "x": 10, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "increase(process_num_threads{job=\"ambientweather\"}[$__interval])"
      }
     ]
    },
    {
     "title": "Requests/min by Status Code",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 5, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "sum by(http_status_code) (increase(ambientweather_api_http_duration_seconds_count[1m]))",
       "legendFormat": "{{http_status_code}}"
      }
     ]
    },
    {
     "title": "HTTP 99th ART",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 5, "x": 5, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le, http_host) (rate(ambientweather_api_http_duration_seconds_bucket[1m])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Generation Memory Collection Count /min",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 6, "x": 10, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(dotnet_collection_count_total{job=\"ambientweather\"}[1m])",
       "legendFormat": "{{generation}}"
      }
     ]
    },
    {
     "title": "DotNet Exceptions/min",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(dotnet_exceptions_total{job=\"ambientweather\"}[1m])",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Scrape Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 29 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "up{job=\"ambientweather\"}"
      }
     ]
    },
    {
     "title": "Samples Scraped",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 3, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "scrape_samples_scraped{job=\"ambientweather\"}"
      }
     ]
    },
    {
     "title": "Scrape Duration Seconds",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 17, "x": 7, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "irate(scrape_duration_seconds{job=\"ambientweather\"}[$__rate_interval])"
      }
     ]
    }
   ]
  }
 ]
}