version: "3.9"

services:
  ambient-weather:
    container_name: ambient-weather-server
    image: philosowaffle/ambientweather-local-server:latest
    ports:
      - 8001:8080
    environment:
      - TZ=America/Chicago
    volumes:
      - ./api.configuration.local.json:/app/configuration.local.json
      - ./data:/app/data # recommended for saving settings across restarts
      - ./output:/app/output # optional, if you configure logs to write to file, they will be found here

  ambient-weather-webui:
    container_name: ambient-weather-webui
    image: philosowaffle/ambientweather-local-server:latest
    command: webui
    ports:
      - 8002:8080
    environment:
      - TZ=America/Chicago
    volumes:
      - ./webui.configuration.local.json:/app/configuration.local.json