version: "3.9"

services:
  ambient-weather:
    container_name: ambient-weather-server
    image: philosowaffle/ambientweather-local-server:latest
    ports:
      - 8001:8080
    environment:
      - TZ=America/Chicago
    volumes:
      - ./api.configuration.local.json:/app/configuration.local.json:ro
      - ./output:/app/output # optional, logs may be written here based on your configuration