namespace Common.Contracts;

/// <summary>
/// https://ambientweather.com/faqs/question/view/id/1857/
/// </summary>
public record AmbientWeatherMetricsPostRequest : IAmbientWeatherMetrics
{
	public Source Source => Source.Local;

	public string? Mac { get; init; }
	public string? StationType { get; init; }
	public string? PassKey { get; init; }
	public DateTime? DateUtc { get; init; }
	public short? WindDir { get; init; }
	public float? WindSpeedMph { get; init; }
	public float? WindGustMph { get; init; }
	public short? WindGustDir { get; init; }
	public float? MaxDailyGust { get; init; }
	public float? WindSpdMph_Avg2m { get; init; }
	public short? WindDir_Avg2m { get; init; }
	public float? WindSpdMph_Avg10m { get; init; }
	public short? WindDir_Avg10m { get; init; }
	public short? WindGustMph_Interval { get; init; }
	public short? Humidity { get; init; }
	public short? HumidityIn { get; init; }
	public short? Humidity1 { get; init; }
	public short? Humidity2 { get; init; }
	public short? Humidity3 { get; init; }
	public short? Humidity4 { get; init; }
	public short? Humidity5 { get; init; }
	public short? Humidity6 { get; init; }
	public short? Humidity7 { get; init; }
	public short? Humidity8 { get; init; }
	public short? Humidity9 { get; init; }
	public short? Humidity10 { get; init; }
	public float? TempF { get; init; }
	public float? TempInF { get; init; }
	public float? Temp1F { get; init; }
	public float? Temp2F { get; init; }
	public float? Temp3F { get; init; }
	public float? Temp4F { get; init; }
	public float? Temp5F { get; init; }
	public float? Temp6F { get; init; }
	public float? Temp7F { get; init; }
	public float? Temp8F { get; init; }
	public float? Temp9F { get; init; }
	public float? Temp10F { get; init; }
	public float? HourlyRainIn { get; init; }
	public float? DailyRainIn { get; init; }
	public float? TwentyFourHourRainIn { get; init; }
	public float? WeeklyRainIn { get; init; }
	public float? MonthlyRainIn { get; init; }
	public float? YearlyRainIn { get; init; }
	public float? EventRainIn { get; init; }
	public float? TotalRain { get; init; }
	public float? BaromRelIn { get; init; }
	public float? BaromAbsIn { get; init; }
	public short? UV { get; init; }
	public float? SolarRadiation { get; init; }
	public short? CO2 { get; init; }
	public short? PM25 { get; init; }
	public float? PM25_24h { get; init; }
	public short? PM25_In { get; init; }
	public float? PM25_In_24h { get; init; }
	public short? PM10_In { get; init; }
	public float? PM10_In_24h { get; init; }
	public short? CO2_In { get; init; }
	public float? CO2_In_24h { get; init; }
	public float? PM_In_Temp { get; init; }
	public short? PM_In_Humidity { get; init; }
	public BoolEnum? Relay1 { get; init; }
	public BoolEnum? Relay2 { get; init; }
	public BoolEnum? Relay3 { get; init; }
	public BoolEnum? Relay4 { get; init; }
	public BoolEnum? Relay5 { get; init; }
	public BoolEnum? Relay6 { get; init; }
	public BoolEnum? Relay7 { get; init; }
	public BoolEnum? Relay8 { get; init; }
	public BoolEnum? Relay9 { get; init; }
	public BoolEnum? Relay10 { get; init; }
	public float? SoilTemp1 { get; init; }
	public float? SoilTemp2 { get; init; }
	public float? SoilTemp3 { get; init; }
	public float? SoilTemp4 { get; init; }
	public float? SoilTemp5 { get; init; }
	public float? SoilTemp6 { get; init; }
	public float? SoilTemp7 { get; init; }
	public float? SoilTemp8 { get; init; }
	public float? SoilTemp9 { get; init; }
	public float? SoilTemp10 { get; init; }
	public short? SoilHum1 { get; init; }
	public short? SoilHum2 { get; init; }
	public short? SoilHum3 { get; init; }
	public short? SoilHum4 { get; init; }
	public short? SoilHum5 { get; init; }
	public short? SoilHum6 { get; init; }
	public short? SoilHum7 { get; init; }
	public short? SoilHum8 { get; init; }
	public short? SoilHum9 { get; init; }
	public short? SoilHum10 { get; init; }
	public LeakSensorState? Leak1 { get; init; }
	public LeakSensorState? Leak2 { get; init; }
	public LeakSensorState? Leak3 { get; init; }
	public LeakSensorState? Leak4 { get; init; }
	public ulong? Lightning_Time { get; init; }
	public short? Lightning_Day { get; init; }
	public BoolEnum? Lightning_Distance { get; init; }
	public BoolEnum? LowBattery { get; init; }
	public BoolEnum? NormalBattery { get; init; }
	public BoolEnum? BattOut { get; init; }
	public BoolEnum? BattIn { get; init; }
	public BoolEnum? Batt1 { get; init; }
	public BoolEnum? Batt2 { get; init; }
	public BoolEnum? Batt3 { get; init; }
	public BoolEnum? Batt4 { get; init; }
	public BoolEnum? Batt5 { get; init; }
	public BoolEnum? Batt6 { get; init; }
	public BoolEnum? Batt7 { get; init; }
	public BoolEnum? Batt8 { get; init; }
	public BoolEnum? Batt9 { get; init; }
	public BoolEnum? Batt10 { get; init; }
	public BoolEnum? BattR1 { get; init; }
	public BoolEnum? BattR2 { get; init; }
	public BoolEnum? BattR3 { get; init; }
	public BoolEnum? BattR4 { get; init; }
	public BoolEnum? BattR5 { get; init; }
	public BoolEnum? BattR6 { get; init; }
	public BoolEnum? BattR7 { get; init; }
	public BoolEnum? BattR8 { get; init; }
	public BoolEnum? BattR9 { get; init; }
	public BoolEnum? BattR10 { get; init; }
	public BoolEnum? Batt_25 { get; init; }
	public BoolEnum? Batt_25In { get; init; }
	public BoolEnum? BatLeak1 { get; init; }
	public BoolEnum? BatLeak2 { get; init; }
	public BoolEnum? BatLeak3 { get; init; }
	public BoolEnum? BatLeak4 { get; init; }
	public BoolEnum? Batt_Lightning { get; init; }
	public BoolEnum? BattSM1 { get; init; }
	public BoolEnum? BattSM2 { get; init; }
	public BoolEnum? BattSM3 { get; init; }
	public BoolEnum? BattSM4 { get; init; }
	public BoolEnum? BattRain { get; init; }
	public BoolEnum? Batt_Co2 { get; init; }
	public float? DewPoint { get; init; }
	public float? DewPoint1 { get; init; }
	public float? DewPoint2 { get; init; }
	public float? DewPoint3 { get; init; }
	public float? DewPoint4 { get; init; }
	public float? DewPoint5 { get; init; }
	public float? DewPoint6 { get; init; }
	public float? DewPoint7 { get; init; }
	public float? DewPoint8 { get; init; }
	public float? DewPoint9 { get; init; }
	public float? DewPoint10 { get; init; }
	public float? DewPointIn { get; init; }
	public float? FeelsLike { get; init; }
	public float? FeelsLike1 { get; init; }
	public float? FeelsLike2 { get; init; }
	public float? FeelsLike3 { get; init; }
	public float? FeelsLike4 { get; init; }
	public float? FeelsLike5 { get; init; }
	public float? FeelsLike6 { get; init; }
	public float? FeelsLike7 { get; init; }
	public float? FeelsLike8 { get; init; }
	public float? FeelsLike9 { get; init; }
	public float? FeelsLike10 { get; init; }
	public float? FeelsLikeIn { get; init; }
}
