name: Publish Docker Latest

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - 'src/**'
    - 'docker/**'
    - 'api.configuration.example.json'
    - 'webui.configuration.example.json'
    - '.github/workflows/docker_latest.yml'

jobs:

  docker-image:
    name: Publish Docker API - Latest
    runs-on: ubuntu-latest

    steps:

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Prepare env
        run: |
          echo "BUILD_VERSION=${GITHUB_RUN_NUMBER}-${GITHUB_RUN_ID}" >> $GITHUB_ENV

      - name: Build & Push to DockerHub
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: true
          file: ./docker/Dockerfile
          tags: ${{ secrets.DOCKER_USERNAME }}/ambientweather-local-server:latest
          platforms: linux/arm64,linux/amd64
          build-args: VERSION=${{ env.BUILD_VERSION }}
          
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}