name: PR Check

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:

  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        dotnet: [ '6.0']
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:

    - uses: actions/checkout@v2

    - name: Setup .NET Core SDK ${{ matrix.dotnet }}
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: ${{ matrix.dotnet }}

    - name: Clean
      run: dotnet clean --configuration Debug && dotnet nuget locals all --clear
    
    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Debug

    - name: Test
      run: dotnet test
 
  create-test-image:
   name: Publish Docker - PR
   runs-on: ubuntu-latest

   steps:

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Prepare env
      run: |
       echo "BUILD_VERSION=${GITHUB_RUN_NUMBER}-${GITHUB_RUN_ID}" >> $GITHUB_ENV

    - name: Build & Push to DockerHub
      id: docker_build
      uses: docker/build-push-action@v3
      with:
      push: true
      file: ./docker/Dockerfile
      tags: ${{ secrets.DOCKER_USERNAME }}/ambientweather-local-server:pr
      platforms: linux/arm64,linux/amd64
      build-args: VERSION=${{ env.BUILD_VERSION }}
          
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}